version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: backend
    depends_on:
      - db
    ports: 
      - "8345:8000"
    volumes:
      - type: bind
        source: /mnt/d/Projects/DriveReader/app
        target: /project
    working_dir: /project


  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    container_name: postgres-db
    ports:
      - "54320:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d


  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: front-end
    depends_on:
      - backend
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: /mnt/d/Projects/DriveReader/frontend
        target: /project
    working_dir: /project
    restart:
      on-failure[:5]