version: "3"

services:
  app:
    image: python
    container_name: drive-reader
    ports: 
      - 8000:8000
    volumes:
      - type: bind
        source: /mnt/d/Projects/DriveReader/app
        target: /project
    working_dir: /project
    command: sh start.sh


  db:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_pass
      - POSTGRES_DB=postgres
    ports:
      - 54320:5432
    volumes:
      - ./db/pgdump.sql:/docker-entrypoint-initdb.d/initdb.sql