version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: drive-reader
    depends_on:
      - db
    ports: 
      - "8000:8000"
    volumes:
      - type: bind
        source: /mnt/d/Projects/DriveReader/app
        target: /project
    working_dir: /project


  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    container_name: postgres-db
    ports:
      - "54320:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d