apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-dash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-dash
  template:
    metadata:
      labels:
        app: expense-dash
    spec:
      volumes:
        - name: expense-dash-data
          hostPath:
            path: /run/desktop/mnt/host/d/Projects/DriveReader/dash
      containers:
      - name: expense-container-dash
        image: lexxo/test:frontend
        workingDir: /project
        command: ["python"]
        args: ["src/main.py"]
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: expense-dash-data
            mountPath: /project

---

apiVersion: v1
kind: Service
metadata:
  name: expense-dash-expose
spec:
  selector:
    app: expense-dash
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: LoadBalancer