apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-postgres-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/d/Projects/DriveReader/kube/volume

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-postgres-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---